package mc.sn.day7;

public class TestException {

	public static void main(String[] args) {
		TestException te = new TestException();
		te.test1();
	}
	public void test1() {
		System.out.println("test1");
		int a = 0;
		try {
			int c = 10/a;	
		}catch(ArithmeticException e) {
			System.out.println("에러 발생"+e.getMessage());
		}
		
		System.out.println(c);
	}
}
